-- =============================================================================
-- Food / Supabase schema init
-- =============================================================================
-- 说明：
-- - 这是给“新项目”一次性执行的初始化脚本（可重复执行尽量不报错）。
-- - 包含当前前端依赖的表/字段/函数（RPC）/RLS 策略。
-- - 执行后记得把 allowed_email_suffixes 里的默认后缀改成你自己的。

-- Extensions
CREATE EXTENSION IF NOT EXISTS postgis;

-- =============================================================================
-- Tables
-- =============================================================================

-- 餐厅信息
CREATE TABLE IF NOT EXISTS shops (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gaode_id TEXT UNIQUE,
  name TEXT NOT NULL,
  location GEOGRAPHY(POINT, 4326),
  rating NUMERIC DEFAULT 0,
  avg_price NUMERIC,
  tag TEXT,
  logo TEXT,
  deepinfo JSONB
);

CREATE INDEX IF NOT EXISTS idx_shops_location ON shops USING GIST (location);

-- 投票房间
CREATE TABLE IF NOT EXISTS vote_rooms (
  room_code TEXT PRIMARY KEY,
  room_name TEXT,
  candidates JSONB NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  expires_at TIMESTAMP WITH TIME ZONE,
  is_active BOOLEAN DEFAULT true,
  created_by UUID NOT NULL DEFAULT auth.uid()
);

COMMENT ON COLUMN vote_rooms.room_name IS '房间名称（可选）';
COMMENT ON COLUMN vote_rooms.expires_at IS '房间过期时间，NULL 表示永不过期';
COMMENT ON COLUMN vote_rooms.is_active IS '房间是否活跃，false 表示已解散';
COMMENT ON COLUMN vote_rooms.created_by IS '创建者用户ID';

-- 兼容旧表：如果 vote_rooms 早期版本没有这些字段，重复执行本脚本时补齐
ALTER TABLE vote_rooms
  ADD COLUMN IF NOT EXISTS room_name TEXT;
ALTER TABLE vote_rooms
  ADD COLUMN IF NOT EXISTS expires_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE vote_rooms
  ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true;
ALTER TABLE vote_rooms
  ADD COLUMN IF NOT EXISTS created_by UUID;

CREATE INDEX IF NOT EXISTS idx_vote_rooms_active
  ON vote_rooms(is_active)
  WHERE is_active = true;

CREATE INDEX IF NOT EXISTS idx_vote_rooms_expires_at
  ON vote_rooms(expires_at)
  WHERE expires_at IS NOT NULL;

-- 投票记录
CREATE TABLE IF NOT EXISTS vote_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_code TEXT REFERENCES vote_rooms(room_code) ON DELETE CASCADE,
  shop_id BIGINT,
  voter_id TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  UNIQUE(room_code, voter_id)
);

-- 用户常用位置
CREATE TABLE IF NOT EXISTS user_locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  lat FLOAT NOT NULL,
  lng FLOAT NOT NULL,
  is_default BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  UNIQUE(user_id, name)
);

CREATE INDEX IF NOT EXISTS idx_user_locations_user_id ON user_locations(user_id);

-- 邮箱后缀白名单（前端也会校验，这里用于 RLS 兜底）
CREATE TABLE IF NOT EXISTS allowed_email_suffixes (
  suffix TEXT PRIMARY KEY,
  CONSTRAINT allowed_email_suffixes_suffix_format CHECK (suffix LIKE '@%')
);

-- TODO: 替换成你自己的邮箱后缀（例如 '@yourcompany.com'）
INSERT INTO allowed_email_suffixes (suffix)
VALUES ('@example.com')
ON CONFLICT (suffix) DO NOTHING;

-- =============================================================================
-- Functions (RPC)
-- =============================================================================

-- 判断当前登录用户邮箱是否在白名单后缀中
CREATE OR REPLACE FUNCTION is_allowed_email()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM allowed_email_suffixes s
    WHERE lower(
      right(
        coalesce(current_setting('request.jwt.claims', true)::jsonb ->> 'email', ''),
        length(s.suffix)
      )
    ) = lower(s.suffix)
  );
$$;

-- 附近餐厅（不含标签过滤；保留作简化接口/调试用）
CREATE OR REPLACE FUNCTION get_nearby_shops(
  lat FLOAT,
  lng FLOAT,
  radius_meters INT DEFAULT 2000,
  limit_count INT DEFAULT 50
)
RETURNS TABLE (
  id BIGINT,
  name TEXT,
  rating NUMERIC,
  avg_price NUMERIC,
  tag TEXT,
  logo TEXT,
  dist_meters FLOAT
)
LANGUAGE sql
AS $$
  SELECT
    id, name, rating, avg_price, tag, logo,
    ST_Distance(location, ST_Point(lng, lat)::geography) AS dist_meters
  FROM shops
  WHERE ST_DWithin(location, ST_Point(lng, lat)::geography, radius_meters)
  ORDER BY dist_meters ASC
  LIMIT limit_count;
$$;

-- 标签统计（用于前端筛选）
CREATE OR REPLACE FUNCTION get_all_tags()
RETURNS TABLE (
  tag TEXT,
  count BIGINT
)
LANGUAGE sql
AS $$
  SELECT
    TRIM(t) AS tag,
    COUNT(*) AS count
  FROM shops,
    unnest(string_to_array(coalesce(tag, ''), ';')) AS t
  WHERE TRIM(t) <> ''
  GROUP BY TRIM(t)
  ORDER BY count DESC, tag ASC
  LIMIT 50;
$$;

-- 支持多标签包含/排除的查询（前端实际使用）
-- include_tags: 店铺标签至少命中其中一个；exclude_tags: 店铺标签不能命中其中任何一个
-- name_query: 餐厅名称模糊搜索（不区分大小写）
CREATE OR REPLACE FUNCTION get_shops_with_tag_filters(
  center_lat float,
  center_lng float,
  radius_meters int default 2000,
  offset_count int default 0,
  limit_count int default 50,
  include_tags text[] default null,
  exclude_tags text[] default null,
  name_query text default null
)
RETURNS TABLE (
  id bigint,
  name text,
  rating numeric,
  avg_price numeric,
  tag text,
  logo text,
  deepinfo text,
  dist_meters float
)
LANGUAGE sql
AS $$
  SELECT
    id,
    name,
    rating,
    avg_price,
    tag,
    logo,
    deepinfo,
    st_distance(location, st_point(center_lng, center_lat)::geography) as dist_meters
  FROM shops
  WHERE
    st_dwithin(location, st_point(center_lng, center_lat)::geography, radius_meters)
    AND (
      include_tags IS NULL
      OR EXISTS (
        SELECT 1
        FROM unnest(string_to_array(coalesce(tag, ''), ';')) AS shop_tag
        WHERE TRIM(shop_tag) <> '' AND TRIM(shop_tag) = ANY(include_tags)
      )
    )
    AND (
      exclude_tags IS NULL
      OR NOT EXISTS (
        SELECT 1
        FROM unnest(string_to_array(coalesce(tag, ''), ';')) AS shop_tag
        WHERE TRIM(shop_tag) <> '' AND TRIM(shop_tag) = ANY(exclude_tags)
      )
    )
    AND (
      name_query IS NULL
      OR name ILIKE '%' || name_query || '%'
    )
  ORDER BY dist_meters ASC
  OFFSET offset_count
  LIMIT limit_count;
$$;

-- 房间详情（返回 room + votes；包含投票者邮箱）
CREATE OR REPLACE FUNCTION get_room_details(room_code_param TEXT)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  room_info JSON;
  votes_data JSON;
BEGIN
  IF NOT is_allowed_email() THEN
    RAISE EXCEPTION 'not allowed' USING ERRCODE = '28000';
  END IF;

  SELECT json_build_object(
    'room_code', room_code,
    'room_name', room_name,
    'candidates', candidates,
    'created_at', created_at,
    'expires_at', expires_at,
    'is_active', is_active,
    'created_by', created_by
  )
  INTO room_info
  FROM vote_rooms
  WHERE room_code = room_code_param;

  IF room_info IS NULL THEN
    RETURN NULL;
  END IF;

  SELECT json_agg(json_build_object(
    'voter_id', voter_id,
    'shop_id', shop_id,
    'voter_email', (
      SELECT email
      FROM auth.users
      WHERE auth.users.id::text = vote_records.voter_id
    )
  ))
  INTO votes_data
  FROM vote_records
  WHERE room_code = room_code_param;

  RETURN json_build_object(
    'room', room_info,
    'votes', COALESCE(votes_data, '[]'::json)
  );
END;
$$;

-- 获取当前用户创建的活跃房间列表（前端“我的房间”）
CREATE OR REPLACE FUNCTION get_my_rooms()
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  rooms_data JSON;
BEGIN
  IF NOT is_allowed_email() THEN
    RAISE EXCEPTION 'not allowed' USING ERRCODE = '28000';
  END IF;

  SELECT json_agg(json_build_object(
    'room_code', vr.room_code,
    'room_name', vr.room_name,
    'created_at', vr.created_at,
    'expires_at', vr.expires_at,
    'is_active', vr.is_active,
    'candidates_count', jsonb_array_length(vr.candidates),
    'votes_count', (
      SELECT COUNT(*)
      FROM vote_records
      WHERE room_code = vr.room_code
    )
  ))
  INTO rooms_data
  FROM (
    SELECT *
    FROM vote_rooms
    WHERE created_by = auth.uid()
      AND is_active = true
    ORDER BY created_at DESC
  ) vr;

  RETURN COALESCE(rooms_data, '[]'::json);
END;
$$;

-- 检查房间是否有效（未解散且未过期）
CREATE OR REPLACE FUNCTION is_room_valid(room_code_param TEXT)
RETURNS BOOLEAN
LANGUAGE plpgsql
AS $$
DECLARE
  room_expires_at TIMESTAMP WITH TIME ZONE;
  room_is_active BOOLEAN;
BEGIN
  SELECT expires_at, is_active
  INTO room_expires_at, room_is_active
  FROM vote_rooms
  WHERE room_code = room_code_param;

  IF NOT FOUND THEN
    RETURN FALSE;
  END IF;

  IF COALESCE(room_is_active, true) = FALSE THEN
    RETURN FALSE;
  END IF;

  IF room_expires_at IS NOT NULL AND room_expires_at < timezone('utc'::text, now()) THEN
    RETURN FALSE;
  END IF;

  RETURN TRUE;
END;
$$;

-- user_locations: 自动更新 updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = timezone('utc'::text, now());
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS update_user_locations_updated_at ON user_locations;
CREATE TRIGGER update_user_locations_updated_at
  BEFORE UPDATE ON user_locations
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- =============================================================================
-- Realtime
-- =============================================================================

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND schemaname = 'public'
      AND tablename = 'vote_records'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.vote_records;
  END IF;
END $$;

-- =============================================================================
-- RLS
-- =============================================================================

ALTER TABLE shops ENABLE ROW LEVEL SECURITY;
ALTER TABLE vote_rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE vote_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_locations ENABLE ROW LEVEL SECURITY;

-- shops: 只允许白名单邮箱的已登录用户读取
DROP POLICY IF EXISTS "Allow public read shops" ON shops;
DROP POLICY IF EXISTS "Allow authenticated read shops" ON shops;
CREATE POLICY "Allow authenticated read shops"
ON shops
FOR SELECT
TO authenticated
USING (is_allowed_email());

-- vote_rooms: 创建/读取/更新（创建者）
DROP POLICY IF EXISTS "Allow public create rooms" ON vote_rooms;
DROP POLICY IF EXISTS "Allow public read rooms" ON vote_rooms;
DROP POLICY IF EXISTS "Allow authenticated create rooms" ON vote_rooms;
DROP POLICY IF EXISTS "Allow authenticated read rooms" ON vote_rooms;
CREATE POLICY "Allow authenticated create rooms"
ON vote_rooms
FOR INSERT
TO authenticated
WITH CHECK (is_allowed_email() AND created_by = auth.uid());

CREATE POLICY "Allow authenticated read rooms"
ON vote_rooms
FOR SELECT
TO authenticated
USING (is_allowed_email());

DROP POLICY IF EXISTS "Allow authenticated update own rooms" ON vote_rooms;
CREATE POLICY "Allow authenticated update own rooms"
ON vote_rooms
FOR UPDATE
TO authenticated
USING (is_allowed_email() AND created_by = auth.uid())
WITH CHECK (is_allowed_email() AND created_by = auth.uid());

-- vote_records: 读取/投票/改票/删票（只能是自己）
DROP POLICY IF EXISTS "Allow public vote" ON vote_records;
DROP POLICY IF EXISTS "Allow public read votes" ON vote_records;
DROP POLICY IF EXISTS "Allow public delete votes" ON vote_records;
DROP POLICY IF EXISTS "Allow authenticated read votes" ON vote_records;
DROP POLICY IF EXISTS "Allow authenticated vote" ON vote_records;
DROP POLICY IF EXISTS "Allow authenticated update own vote" ON vote_records;
DROP POLICY IF EXISTS "Allow authenticated delete own vote" ON vote_records;

CREATE POLICY "Allow authenticated read votes"
ON vote_records
FOR SELECT
TO authenticated
USING (is_allowed_email());

CREATE POLICY "Allow authenticated vote"
ON vote_records
FOR INSERT
TO authenticated
WITH CHECK (is_allowed_email() AND voter_id = auth.uid()::text);

CREATE POLICY "Allow authenticated update own vote"
ON vote_records
FOR UPDATE
TO authenticated
USING (is_allowed_email() AND voter_id = auth.uid()::text)
WITH CHECK (is_allowed_email() AND voter_id = auth.uid()::text);

CREATE POLICY "Allow authenticated delete own vote"
ON vote_records
FOR DELETE
TO authenticated
USING (is_allowed_email() AND voter_id = auth.uid()::text);

-- user_locations: 仅允许本人访问自己的位置
DROP POLICY IF EXISTS "Allow authenticated read own locations" ON user_locations;
DROP POLICY IF EXISTS "Allow authenticated insert own locations" ON user_locations;
DROP POLICY IF EXISTS "Allow authenticated update own locations" ON user_locations;
DROP POLICY IF EXISTS "Allow authenticated delete own locations" ON user_locations;

CREATE POLICY "Allow authenticated read own locations"
ON user_locations
FOR SELECT
TO authenticated
USING (is_allowed_email() AND auth.uid() = user_id);

CREATE POLICY "Allow authenticated insert own locations"
ON user_locations
FOR INSERT
TO authenticated
WITH CHECK (is_allowed_email() AND auth.uid() = user_id);

CREATE POLICY "Allow authenticated update own locations"
ON user_locations
FOR UPDATE
TO authenticated
USING (is_allowed_email() AND auth.uid() = user_id)
WITH CHECK (is_allowed_email() AND auth.uid() = user_id);

CREATE POLICY "Allow authenticated delete own locations"
ON user_locations
FOR DELETE
TO authenticated
USING (is_allowed_email() AND auth.uid() = user_id);

-- PostGIS 自带表：避免启用 RLS 后产生读取报错
ALTER TABLE "spatial_ref_sys" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read spatial_ref_sys" ON "spatial_ref_sys";
CREATE POLICY "Allow public read spatial_ref_sys"
ON "spatial_ref_sys"
FOR SELECT
TO public
USING (true);

-- =============================================================================
-- Grants
-- =============================================================================

GRANT USAGE ON SCHEMA public TO authenticated;

GRANT SELECT ON TABLE shops TO authenticated;
GRANT SELECT, INSERT, UPDATE ON TABLE vote_rooms TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE vote_records TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE user_locations TO authenticated;
GRANT SELECT ON TABLE allowed_email_suffixes TO authenticated;

GRANT EXECUTE ON FUNCTION get_shops_with_tag_filters(float, float, int, int, int, text[], text[], text) TO authenticated;
GRANT EXECUTE ON FUNCTION get_all_tags() TO authenticated;
GRANT EXECUTE ON FUNCTION get_nearby_shops(float, float, int, int) TO authenticated;
GRANT EXECUTE ON FUNCTION get_room_details(TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION get_my_rooms() TO authenticated;
GRANT EXECUTE ON FUNCTION is_room_valid(TEXT) TO authenticated;
