CREATE EXTENSION IF NOT EXISTS postgis;
CREATE TABLE shops (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 自增ID
    gaode_id TEXT UNIQUE,     -- 高德原始ID (防止重复导入)
    name TEXT NOT NULL,       -- 店名
    
    -- 核心：地理位置 (点坐标, SRID 4326 是 GPS 标准)
    location GEOGRAPHY(POINT, 4326), 
    
    rating NUMERIC DEFAULT 0, -- 评分 (如 4.5)
    avg_price NUMERIC,        -- 人均价格
    tag TEXT,                 -- 标签 (如 "川菜;火锅")
    logo TEXT,                -- 图片链接
    
    -- 可选：存更多详情，如营业时间
    deepinfo JSONB            
);

-- 创建地理索引 (这一步对性能至关重要！)
CREATE INDEX idx_shops_location ON shops USING GIST (location);

CREATE TABLE vote_rooms (
    room_code TEXT PRIMARY KEY, -- 房间号，例如 "8848" 或 "x7z9a"
    
    -- 核心：候选人快照
    -- 数据结构: [{"id": 1, "name": "麦当劳", "vote_count": 0}, ...]
    candidates JSONB NOT NULL,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE vote_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    room_code TEXT REFERENCES vote_rooms(room_code) ON DELETE CASCADE, -- 关联房间
    shop_id BIGINT,  -- 投给了哪个店
    
    -- 核心：防刷票机制
    -- 前端在 LocalStorage 生成一个随机 UUID 作为 voter_id
    voter_id TEXT NOT NULL,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),

    -- 约束：同一个房间，同一个人，只能投一票
    UNIQUE(room_code, voter_id)
);

CREATE OR REPLACE FUNCTION get_nearby_shops(
    lat FLOAT,           -- 中心纬度
    lng FLOAT,           -- 中心经度
    radius_meters INT DEFAULT 2000, -- 搜索半径 (默认2公里)
    limit_count INT DEFAULT 50      -- 返回数量
)
RETURNS TABLE (
    id BIGINT,
    name TEXT,
    rating NUMERIC,
    avg_price NUMERIC,
    tag TEXT,
    logo TEXT,
    dist_meters FLOAT    -- 计算出的距离
)
LANGUAGE sql
AS $$
    SELECT 
        id, name, rating, avg_price, tag, logo,
        -- 计算距离 (单位: 米)
        ST_Distance(location, ST_Point(lng, lat)::geography) AS dist_meters
    FROM 
        shops
    WHERE 
        -- 筛选半径内的点
        ST_DWithin(location, ST_Point(lng, lat)::geography, radius_meters)
    ORDER BY 
        dist_meters ASC -- 按距离排序
    LIMIT 
        limit_count;
$$;

-- 获取所有标签及其统计
CREATE OR REPLACE FUNCTION get_all_tags()
RETURNS TABLE (
    tag TEXT,
    count BIGINT
)
LANGUAGE sql
AS $$
    SELECT
        TRIM(unnest) AS tag,
        COUNT(*) AS count
    FROM (
        SELECT regexp_split_to_array(tag, ';') AS tags_array
        FROM shops
        WHERE tag IS NOT NULL AND tag != ''
    ) subquery,
    unnest(tags_array)
    GROUP BY tag
    ORDER BY count DESC, tag ASC;
$$;

-- 将 vote_records 表加入实时发布列表
ALTER PUBLICATION supabase_realtime ADD TABLE vote_records;

-- 启用 RLS
ALTER TABLE shops ENABLE ROW LEVEL SECURITY;
ALTER TABLE vote_rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE vote_records ENABLE ROW LEVEL SECURITY;

-- Auth-only + 邮箱后缀白名单（前端也会校验，但这里用 RLS 兜底）
CREATE TABLE IF NOT EXISTS allowed_email_suffixes (
    suffix TEXT PRIMARY KEY,
    CONSTRAINT allowed_email_suffixes_suffix_format CHECK (suffix LIKE '@%')
);

-- TODO: 替换成你自己的邮箱后缀（例如 '@yourcompany.com'）
INSERT INTO allowed_email_suffixes (suffix)
VALUES ('@example.com')
ON CONFLICT (suffix) DO NOTHING;

CREATE OR REPLACE FUNCTION is_allowed_email()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM allowed_email_suffixes s
    WHERE lower(
      right(
        coalesce(current_setting('request.jwt.claims', true)::jsonb ->> 'email', ''),
        length(s.suffix)
      )
    ) = lower(s.suffix)
  );
$$;

-- 去掉匿名访问：所有数据访问都要求 authenticated + 邮箱后缀在白名单内
DROP POLICY IF EXISTS "Allow public read shops" ON shops;
CREATE POLICY "Allow authenticated read shops"
ON shops
FOR SELECT
TO authenticated
USING (is_allowed_email());

DROP POLICY IF EXISTS "Allow public create rooms" ON vote_rooms;
DROP POLICY IF EXISTS "Allow public read rooms" ON vote_rooms;
CREATE POLICY "Allow authenticated create rooms"
ON vote_rooms
FOR INSERT
TO authenticated
WITH CHECK (is_allowed_email());
CREATE POLICY "Allow authenticated read rooms"
ON vote_rooms
FOR SELECT
TO authenticated
USING (is_allowed_email());

-- 允许创建者更新自己创建的房间（用于解散/修改名称/调整过期时间等）
DROP POLICY IF EXISTS "Allow authenticated update own rooms" ON vote_rooms;
CREATE POLICY "Allow authenticated update own rooms"
ON vote_rooms
FOR UPDATE
TO authenticated
USING (is_allowed_email() AND created_by = auth.uid())
WITH CHECK (is_allowed_email() AND created_by = auth.uid());

DROP POLICY IF EXISTS "Allow public vote" ON vote_records;
DROP POLICY IF EXISTS "Allow public read votes" ON vote_records;
DROP POLICY IF EXISTS "Allow public delete votes" ON vote_records;

CREATE POLICY "Allow authenticated read votes"
ON vote_records
FOR SELECT
TO authenticated
USING (is_allowed_email());

-- upsert 会走 INSERT + UPDATE，因此需要 UPDATE policy
CREATE POLICY "Allow authenticated vote"
ON vote_records
FOR INSERT
TO authenticated
WITH CHECK (is_allowed_email() AND voter_id = auth.uid()::text);

CREATE POLICY "Allow authenticated update own vote"
ON vote_records
FOR UPDATE
TO authenticated
USING (is_allowed_email() AND voter_id = auth.uid()::text)
WITH CHECK (is_allowed_email() AND voter_id = auth.uid()::text);

CREATE POLICY "Allow authenticated delete own vote"
ON vote_records
FOR DELETE
TO authenticated
USING (is_allowed_email() AND voter_id = auth.uid()::text);


-- 1. 开启行级安全策略 (消除报错的核心)
ALTER TABLE "spatial_ref_sys" ENABLE ROW LEVEL SECURITY;

-- 2. 创建一条策略：允许所有人读取
-- (因为这是地图标准数据，前端地图组件有时可能需要读取它，公开读是安全的)
CREATE POLICY "Allow public read spatial_ref_sys"
ON "spatial_ref_sys"
FOR SELECT
TO public
USING (true);


CREATE OR REPLACE FUNCTION get_all_tags()
RETURNS TABLE (
    tag TEXT,
    count BIGINT
)
LANGUAGE sql
AS $$
    SELECT 
        TRIM(t) AS tag,     -- 去除前后空格
        COUNT(*) AS count
    FROM shops, 
    unnest(string_to_array(tag, ';')) AS t -- 直接拆分
    WHERE 
        tag IS NOT NULL 
        AND TRIM(t) <> '' -- 确保拆分后不是空字符串
    GROUP BY TRIM(t)
    ORDER BY count DESC, tag ASC
    LIMIT 50; -- 建议加个限制，只取最热门的50个，防止前端渲染太多卡顿
$$;


-- 修改后的查询函数，增加了 filter_tag 参数
CREATE OR REPLACE FUNCTION get_shops_fixed(
  center_lat float, 
  center_lng float, 
  radius_meters int default 2000, 
  limit_count int default 50,
  filter_tag text default null -- 新增参数，默认为空
)
RETURNS TABLE (
  id bigint, 
  name text, 
  rating numeric, 
  avg_price numeric, 
  tag text,
  logo text,
  dist_meters float
)
LANGUAGE sql
AS $$
  SELECT 
    id, name, rating, avg_price, tag, logo,
    st_distance(location, st_point(center_lng, center_lat)::geography) as dist_meters
  FROM shops
  WHERE 
    st_dwithin(location, st_point(center_lng, center_lat)::geography, radius_meters)
    AND (
        filter_tag IS NULL -- 如果没传标签，就不过滤
        OR 
        tag ILIKE '%' || filter_tag || '%' -- 如果传了，就模糊匹配 (包含该标签)
    )
  ORDER BY 
    dist_meters ASC
  LIMIT limit_count;
$$;


-- 先删除旧函数（因为返回类型改变）
DROP FUNCTION IF EXISTS get_shops_with_tag_filters(double precision, double precision, integer, integer, integer, text[], text[]);

-- 支持多标签包含/排除的查询函数
CREATE OR REPLACE FUNCTION get_shops_with_tag_filters(
  center_lat float,
  center_lng float,
  radius_meters int default 2000,
  offset_count int default 0,
  limit_count int default 50,
  include_tags text[] default null,  -- 包含的标签数组（任一匹配即可）
  exclude_tags text[] default null  -- 排除的标签数组（全部不匹配）
)
RETURNS TABLE (
  id bigint,
  name text,
  rating numeric,
  avg_price numeric,
  tag text,
  logo text,
  deepinfo text,
  dist_meters float
)
LANGUAGE sql
AS $$
  SELECT
    id, name, rating, avg_price, tag, logo, deepinfo,
    st_distance(location, st_point(center_lng, center_lat)::geography) as dist_meters
  FROM shops
  WHERE
    st_dwithin(location, st_point(center_lng, center_lat)::geography, radius_meters)
    -- 包含标签过滤：如果有 include_tags，店铺标签必须至少包含其中一个
    AND (
      include_tags IS NULL
      OR EXISTS (
        SELECT 1 FROM unnest(string_to_array(tag, ';')) AS shop_tag
        WHERE TRIM(shop_tag) = ANY(include_tags)
      )
    )
    -- 排除标签过滤：如果有 exclude_tags，店铺标签不能包含其中任何一个
    AND (
      exclude_tags IS NULL
      OR NOT EXISTS (
        SELECT 1 FROM unnest(string_to_array(tag, ';')) AS shop_tag
        WHERE TRIM(shop_tag) = ANY(exclude_tags)
      )
    )
  ORDER BY
    dist_meters ASC
  OFFSET offset_count
  LIMIT limit_count;
$$;
