-- 用户位置表
CREATE TABLE IF NOT EXISTS user_locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE, -- 关联用户
    name TEXT NOT NULL,                -- 位置名称（如"公司"、"家"）
    lat FLOAT NOT NULL,                -- 纬度
    lng FLOAT NOT NULL,                -- 经度
    is_default BOOLEAN DEFAULT FALSE,  -- 是否为默认位置
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),

    -- 每个用户的位置名称唯一
    UNIQUE(user_id, name)
);

-- 创建索引
CREATE INDEX IF NOT EXISTS idx_user_locations_user_id ON user_locations(user_id);

-- 启用 RLS
ALTER TABLE user_locations ENABLE ROW LEVEL SECURITY;

-- 用户可以查看自己的位置
CREATE POLICY "Allow authenticated read own locations"
ON user_locations
FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

-- 用户可以创建自己的位置
CREATE POLICY "Allow authenticated insert own locations"
ON user_locations
FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

-- 用户可以更新自己的位置
CREATE POLICY "Allow authenticated update own locations"
ON user_locations
FOR UPDATE
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- 用户可以删除自己的位置
CREATE POLICY "Allow authenticated delete own locations"
ON user_locations
FOR DELETE
TO authenticated
USING (auth.uid() = user_id);

-- 自动更新 updated_at 的触发器
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_user_locations_updated_at
    BEFORE UPDATE ON user_locations
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
